OnurSpor/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from database import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name = "index"),
    path('about/', views.about,name = "about"),
    path('databases/',include("database.urls")),
    path('user/',include("user.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

database/urls.py
from . import views

from django.contrib import admin
from django.urls import path,include


app_name = "database"


urlpatterns = [
    path('clubdetails/', views.clubdetails,name = "clubdetails"),

    path('editplayer/', views.EditPlayer,name = "editplayer"),
    path('addplayer/', views.AddPlayer,name = "addplayer"),
    path('updateplayer/<int:id>', views.UpdatePlayer,name = "updateplayer"),
    path('deleteplayer/<int:id>', views.DeletePlayer,name = "deleteplayer"),
    
    path('editgaleri/', views.EditGaleri,name = "editgaleri"),
    path('addgaleri/', views.AddGaleri,name = "addgaleri"),
    path('updategaleri/<int:id>', views.UpdateGaleri,name = "updategaleri"),
    path('deletegaleri/<int:id>', views.DeleteGaleri,name = "deletegaleri"),
    
    path('editduyuru/', views.EditDuyuru,name = "editduyuru"),
    path('addduyuru/', views.AddDuyuru,name = "addduyuru"),
    path('updateduyuru/<int:id>', views.UpdateDuyuru,name = "updateduyuru"),
    path('deleteduyuru/<int:id>', views.DeleteDuyuru,name = "deleteduyuru"),

    path('edithaber/', views.EditHaber,name = "edithaber"),
    path('addhaber/', views.AddHaber,name = "addhaber"),
    path('updatehaber/<int:id>', views.UpdateHaber,name = "updatehaber"),
    path('deletehaber/<int:id>', views.DeleteHaber,name = "deletehaber"),

    
    path('puandurumu/', views.EditPuanDurumu,name = "editpuandurumu"),
    path('addpuandurumu/', views.AddPuanDurumu,name = "addpuandurumu"),
    path('updatepuandurumu/<int:id>', views.UpdatePuanDurumu,name = "updatepuandurumu"),
    path('deletepuandurumu/<int:id>', views.DeletePuanDurumu,name = "deletepuandurumu"),

    path('team/<int:id>', views.Team,name = "team"),

    path('sporokulu/', views.SporOkulu,name = "sporokulu"),
    path('basarılarımız/', views.Basarılarımız,name = "basarılarımız"),
    path('galeri', views.Galerii,name = "galeri"),
    path('oyuncularımız/', views.Oyuncularımız,name = "oyuncularımız"),
    path('detail/<int:id>', views.Detail,name = "detail"),
    path('haber_detail/<int:id>', views.HaberDetail,name = "haber_detail"),
    
]

user/urls.py
from . import views

from django.contrib import admin
from django.urls import path

app_name = "user"


urlpatterns = [
    path('login/', views.loginUser,name = "login"),
    path('logout/', views.logoutUser,name = "logout"),
]

templates/includes/navbar.html
{%load static%}
<div>
  <ul style="list-style-type: none;">
      <li style="float:left;"><div style=" "><img src = "{% static 'css/kulüpfoto.png' %}" alt = "Görüntülenemiyor..." wigth = "80" height = "100"></div>	</li> 
      <li style="float:left;"><div style=" "><img src = "{% static 'css/atatürk.png' %}" alt = "Görüntülenemiyor..." wigth = "80" height = "100"></div>	</li> 
      <li style=""><div style=""><img src = "{% static 'css/bayrak.gif' %}" alt = "Görüntülenemiyor..." wigth = "80" height = "100"></div></li> 
      
  
  </ul>
  
</div>

<div style="margin-top:-15px;">
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #e3f2fd; padding:10px;"  >
        <a class="navbar-brand" href="{% url 'index' %}">Anasayfa</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'database:clubdetails' %}">Kulüp <span class="sr-only">(current)</span></a>
            </li>
            
              
            
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'database:galeri' %}">Galeri</a>
              </li>
            
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Takımlar
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'database:team' 1 %}">A Takım</a>
                  <a class="dropdown-item" href="{% url 'database:team' 2 %}">A Genç</a>
                  
                  <a class="dropdown-item" href="{% url 'database:team' 3 %}">U 17</a>
                  <a class="dropdown-item" href="{% url 'database:team' 4 %}">U 16</a>
                  <a class="dropdown-item" href="{% url 'database:team' 5 %}">U 15</a>
                  <a class="dropdown-item" href="{% url 'database:team' 6 %}">U 14</a>
                  <a class="dropdown-item" href="{% url 'database:team' 7 %}">U 13</a>
              </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Diğer
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'database:basarılarımız' %}">Başarılarımız</a>
                    <a class="dropdown-item" href="{% url 'database:sporokulu' %}">Spor Okulu</a>
                    <a class="dropdown-item" href="{% url 'database:oyuncularımız' %}">Oyuncularımız</a>
                    <a class="dropdown-item" href="{% url 'about' %}">Hakkımızda</a>
                </div>
              </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Kontrol Paneli
                </a>
                {% if request.user.is_authenticated %}
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'user:logout' %}">Çıkış Yap</a>
                  
                </div>
                {% else %}
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'user:login' %}">Giriş Yap</a>
                  
                </div>
                {% endif %}
                
                
              </li>
              {% if request.user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Düzenle
            </a>
            
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'database:editpuandurumu' %}">Puan Durumu</a>
              <a class="dropdown-item" href="{% url 'database:editplayer' %}">Oyuncular</a>
              <a class="dropdown-item" href="{% url 'database:editgaleri' %}">Galeri</a>
              <a class="dropdown-item" href="{% url 'database:editduyuru' %}">Duyurular</a>
              <a class="dropdown-item" href="{% url 'database:edithaber' %}">Haberler</a>
              
              
              
            </div>
            
            
            
          </li>
          
          
          {% endif %} 
            <li class="nav-item">
                <form class="form-inline">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                  </form>
              </li>
          </ul>
        </div>
      </nav>
</div>


<div style="font-family:Gabriola; margin-top:5px;">
    <h3 style="font-size:35px; padding-left:40px;">Onur Gençlik Spor Resmi İnternet Platformu</h3>
    <h5 style="padding-left:40px;">İyi Birey; İyi Vatandaş; İyi Futbolcu.</h5>
</div>
<hr>




    










    